[
  {
    "InvestigatorId": 1,
    "Name": "Min Thi Phan",
    "Title": "The Secretary",
    "Lore": 3,
    "Influence": 3,
    "Observation": 3,
    "Strength": 2,
    "Will": 2,
    "Focus": 2,
    "Health": 6,
    "Horror": 6,
    "StartingWealth": 3,
    "AdditionalRules": "All Around You",
    "FlavorText": "I'm certain that if we work together, we can find the solution",
    "StartingItems": "King in Yellow",
    "OptionalItems": "Analytical Mind, Synergy",
    "Role1": "Seeker",
    "Role2": "Survivor"
  },
  {
    "InvestigatorId": 2,
    "Name": "Rex Murphy",
    "Title": "The Reporter",
    "Lore": 3,
    "Influence": 3,
    "Observation": 3,
    "Strength": 2,
    "Will": 2,
    "Focus": -1,
    "Health": 7,
    "Horror": 7,
    "StartingWealth": 3,
    "AdditionalRules": "Family Curse, Never Give Up",
    "FlavorText": "How'd I get mixed up in all this? Just lucky I guess.",
    "StartingItems": "Search for the Truth, The Tower",
    "OptionalItems": "It All Comes Together, Overcome All Odds,",
    "Role1": "Seeker",
    "Role2": "Rogue"
  },
  {
    "InvestigatorId": 3,
    "Name": "Jenny Barnes",
    "Title": "The Dilettante",
    "Lore": 1,
    "Influence": 4,
    "Observation": 2,
    "Strength": 3,
    "Will": 3,
    "Focus": 1,
    "Health": 7,
    "Horror": 5,
    "StartingWealth": 5,
    "AdditionalRules": "Trust Fund",
    "FlavorText": "I'm happy to throw money at the problem, and if that doesn't work I'll throw something else.",
    "StartingItems": "Search for Isabelle",
    "OptionalItems": "Dressed to the Nines, Jenny's Twin .45's",
    "Role1": "Rogue",
    "Role2": "?"
  },
  {
    "InvestigatorId": 4,
    "Name": "Agnes Baker",
    "Title": "The Waitress",
    "Lore": 4,
    "Influence": 2,
    "Observation": 2,
    "Strength": 2,
    "Will": 3,
    "Focus": 2,
    "Health": 6,
    "Horror": 6,
    "StartingWealth": 3,
    "AdditionalRules": "Blood Casting, Blood is Power",
    "FlavorText": "Things aren�t awlays what they seem.",
    "StartingItems": "Heirloom of Hyperborea",
    "OptionalItems": "Storm of Spirits, Flesh Ward",
    "Role1": "Mystic",
    "Role2": "Guardian"
  },
  {
    "InvestigatorId": 5,
    "Name": "Calvin Wright",
    "Title": "The Haunted",
    "Lore": 3,
    "Influence": 3,
    "Observation": 3,
    "Strength": 3,
    "Will": 1,
    "Focus": 2,
    "Health": 6,
    "Horror": 6,
    "StartingWealth": 3,
    "AdditionalRules": "Friend Indeed",
    "FlavorText": "I'll sacrifice everything to keep you safe",
    "StartingItems": "Spirit Dagger, Until the End of Time",
    "OptionalItems": "Voice of the Messanger",
    "Role1": "Guardian",
    "Role2": "Rogue"
  },
  {
    "InvestigatorId": 6,
    "Name": "Tommy Muldoon",
    "Title": "?",
    "Lore": 2,
    "Influence": 2,
    "Observation": 3,
    "Strength": 3,
    "Will": 3,
    "Focus": 2,
    "Health": 7,
    "Horror": 5,
    "StartingWealth": 2,
    "AdditionalRules": "Shield From Harm",
    "FlavorText": "Come on, Tommy. Time to be a hero.",
    "StartingItems": "Becky",
    "OptionalItems": "Handcuffs,?",
    "Role1": "Guardian",
    "Role2": "Survivor"
  },
  {
    "InvestigatorId": 7,
    "Name": "Michael McGlen",
    "Title": "The Mobster",
    "Lore": 2,
    "Influence": 3,
    "Observation": 1,
    "Strength": 4,
    "Will": 3,
    "Focus": 1,
    "Health": 8,
    "Horror": 4,
    "StartingWealth": 3,
    "AdditionalRules": "One for Revenge",
    "FlavorText": "This one's for Louis",
    "StartingItems": "Chichago Typewriter",
    "OptionalItems": "Ol' Boiler, O'Bannion Member",
    "Role1": "Rogue",
    "Role2": "Guardian"
  },
  {
    "InvestigatorId": 8,
    "Name": "Wendy Adams",
    "Title": "The Urchin",
    "Lore": 3,
    "Influence": 1,
    "Observation": 4,
    "Strength": 2,
    "Will": 3,
    "Focus": 3,
    "Health": 5,
    "Horror": 7,
    "StartingWealth": 1,
    "AdditionalRules": "Shortcut",
    "FlavorText": "Someday I'll find my Papa, and Mama will come home with us and we'll be happy again. You'll see.",
    "StartingItems": "Mama's Amulet",
    "OptionalItems": "Mr. Pawterson, Mysterious Photo",
    "Role1": "Survivor",
    "Role2": "Seeker"
  },
  {
    "InvestigatorId": 9,
    "Name": "Daniela Reyes",
    "Title": "The Mechanic",
    "Lore": 3,
    "Influence": 3,
    "Observation": 1,
    "Strength": 3,
    "Will": 3,
    "Focus": 3,
    "Health": 7,
    "Horror": 5,
    "StartingWealth": 3,
    "AdditionalRules": "Love For the Job",
    "FlavorText": "You got a job that needs doing. I'm your girl.",
    "StartingItems": "Gabriel",
    "OptionalItems": "Ace of Swords,?",
    "Role1": "Rogue",
    "Role2": "Survivor"
  },
  {
    "InvestigatorId": 10,
    "Name": "Norman Withers",
    "Title": "The Astronomer",
    "Lore": 3,
    "Influence": 1,
    "Observation": 3,
    "Strength": 2,
    "Will": 4,
    "Focus": 2,
    "Health": 5,
    "Horror": 7,
    "StartingWealth": 1,
    "AdditionalRules": "In the Stars",
    "FlavorText": "Saying 'that's impossible!' doesn't make anything less true. The truth doesn't care what you believe.",
    "StartingItems": "Find Gate",
    "OptionalItems": "Astronomy Book, ?",
    "Role1": "Seeker",
    "Role2": "Mystic"
  },
  {
    "InvestigatorId": 11,
    "Name": "Dexter Drake",
    "Title": "The Magician",
    "Lore": 4,
    "Influence": 3,
    "Observation": 2,
    "Strength": 2,
    "Will": 2,
    "Focus": -2,
    "Health": 5,
    "Horror": 7,
    "StartingWealth": 2,
    "AdditionalRules": "Magical Gift",
    "FlavorText": "You don't want to see real magic, kid. Nobody does.",
    "StartingItems": "Mists of R'lyeh",
    "OptionalItems": "Astral Travel, ?",
    "Role1": "Mystic",
    "Role2": ""
  },
  {
    "InvestigatorId": 12,
    "Name": "Marie Lameau",
    "Title": "The Entertainer",
    "Lore": 3,
    "Influence": 4,
    "Observation": 2,
    "Strength": 2,
    "Will": 2,
    "Focus": 2,
    "Health": 5,
    "Horror": 7,
    "StartingWealth": 4,
    "AdditionalRules": "Smoky Velvet",
    "FlavorText": "Just listen, and I'll sing for you a spell.",
    "StartingItems": "Intervene",
    "OptionalItems": "Witch Blood, Grande-mere's Knife",
    "Role1": "Mystic",
    "Role2": "Survivor"
  }
 ]