var mongoose =  require('mongoose')
var magicItem = mongoose.Schema({
  Name: { type: String },
  Effect: { type: String },
  Implemented: { type: Boolean },
  Aura: { type: String },
  CL: { type: Number },
  ItemType: { type: String },
  Weight: { type: Number },
  Description: { type: String },
  Requirements: { type: String },
  ItemCategory: { type: String },
  Source: { type: String },
  Cost: { type: Number },
  AL: { type: String },
  Int: { type: String },
  Wis: { type: String },
  Cha: { type: String },
  Ego: { type: String },
  Communication: { type: String },
  Senses: { type: String },
  Powers: { type: String },
  MagicItems: { type: String },
  Destruction: { type: String },
  MinorArtifactFlag: { type: String },
  MajorArtifactFlag: { type: String },
  Abjuration: { type: Number },
  Conjuration: { type: Number },
  Divination: { type: Number },
  Enchantment: { type: Number },
  Evocation: { type: Number },
  Necromancy: { type: Number },
  Transmutation: { type: Number },
  AuraStrength: { type: String },
  Languages: { type: String },
  BaseItem: { type: String }
});
module.exports = magicItem;
