var mongoose = require('mongoose'); 
var monster = mongoose.Schema({
  Name: { type: String },
  CR: { type: String },
  Race: { type: Number },
  Classes: { type: Number },
  Alignment	: { type: String },
  Size: { type: String },
  Type: { type: String },
  SubType	: { type: String },
  Init: { type: Number },
  Senses: { type: String },
  Aura: { type: String },
  ACMods: { type: String },
  HP: { type: Number },
  HD: { type: String },
  HPMods: { type: String },
  Fort: { type: Number },
  Ref: { type: Number },
  Will: { type: Number },
  SaveMods: { type: String },
  DefensiveAbilities: { type: String },
  DR: { type: String },
  Immune: { type: String },
  Resist: { type: String },
  SR: { type: Number },
  Weaknesses: { type: String },
  Speed: { type: String },
  Speed_Mod: { type: String },
  Melee: { type: String },
  Ranged: { type: String },
  Reach: { type: String },
  SpecialAttacks: { type: String },
  SpellLikeAbilities: { type: String },
  SpellsKnown	: { type: String },
  SpellsPrepared: { type: String },
  SpellDomains: { type: String },
  AbilityScores	: { type: String },
  BaseAtk	: { type: String },
  Feats: { type: String },
  Skills: { type: String },
  RacialMods: { type: String },
  Languages: { type: String },
  SQ: { type: String },
  Environment: { type: String },
  Organization: { type: String },
  Treasure: { type: String },
  Description_Visual: { type: String },
  Group: { type: String },
  Source: { type: String },
  SpecialAbilities: { type: String },
  Description: { type: String },
  Gear: { type: String },
  Fly: { type: Number },
  Climb: { type: Number },
  Burrow: { type: Number },
  Swim: { type: Number },
  Land: { type: Number },
  DirtySkills: { type: Number }  

});
module.exports = monster;
