var mongoose = require('mongoose'); 
var spell = mongoose.Schema({
  Implemented: { type: Boolean },
  Name: { type: String },
  Duration: { type: String },
  School: { type: String },
  Subschool: { type: String },
  Effect: { type: String },
  EffectType: { type: String },
  SpellType: { type: String },
  CastingTime: { type: String },
  Components: { type: String },
  Range: { type: String },
  Area: { type: String },
  Targets: { type: String },
  SavingThrow: { type: String },
  Harmless: { type: Boolean },
  Resistance: { type: Boolean },
  Description: { type: String },
  Source: { type: String },
  CostlyComponents: { type: Number },
  Dismissible: { type: Number },
  Shapeable: { type: Number },
  Verbal: { type: Number },
  Somatic: { type: Number },
  Material: { type: Number },
  Focus: { type: Number },
  DivineFocus: { type: Number },
  Sorcerer: { type: Number },
  Wizard: { type: Number },
  Cleric: { type: Number },
  Druid: { type: Number },
  Ranger: { type: Number },
  Bard: { type: Number },
  Paladin: { type: Number },
  Alchemist: { type: Number },
  Summoner: { type: Number },
  Witch: { type: Number },
  Inquisitor: { type: Number },
  Oracle: { type: Number },
  Antipaladin: { type: Number },
  Magus: { type: Number },
  SlaLevel: { type: Number },
  Domain: { type: String },
  ShortDescription: { type: String },
});
module.exports = spell;
